title: Documentation
description: Say hello to [ZeroThreat](https://zerothreat.ai/)  a cutting-edge security scanning platform to empower your application security initiatives. With many new exciting features, it has created buzz and excitement among developers and security experts.
