import { FaqCategory } from '~/utils/category.enum'

const tabs = [
  {
    title: 'Getting Started',
    category: FaqCategory['Getting-Started'],
    icon: 'circle-play',
    iconCLass: 'text-blue-400',
    file: 'assets/getting-started.faq.json',
  },
  {
    title: 'Targets',
    category: FaqCategory.Targets,
    icon: 'crosshairs',
    iconCLass: 'text-zt_purple',
    file: 'assets/target.faq.json',
  },
  {
    title: 'Target Verification',
    category: FaqCategory['Target Verification'],
    icon: 'check-double',
    iconCLass: 'text-green-500',
    file: 'assets/target-verification.faq.json',
  },
  {
    title: 'Organization',
    category: FaqCategory.Organizations,
    icon: 'building',
    iconCLass: 'text-yellow-500',
    file: 'assets/organization.faq.json',
  },
  {
    title: 'Authenticate',
    category: FaqCategory['Authenticate'],
    icon: 'shield-halved',
    iconCLass: 'text-green-500',
    file: 'assets/authenticate.faq.json',
  },
  {
    title: 'Unauthenticate',
    category: FaqCategory['Unauthenticate'],
    icon: 'shield-virus',
    iconCLass: 'text-red-500',
    file: 'assets/unauthenticate.faq.json',
  },
  {
    title: 'Product',
    category: FaqCategory.Product,
    icon: 'cube',
    iconCLass: 'text-stone-500',
    file: 'assets/product.faq.json',
  },
  {
    title: 'Scan',
    category: FaqCategory.Scan,
    icon: 'expand',
    iconCLass: 'text-blue-500',
    file: 'assets/scan.faq.json',
  },
  {
    title: 'API Security',
    category: FaqCategory['API Security'],
    icon: 'key',
    iconCLass: 'text-green-500',
    file: 'assets/api-security.faq.json',
  },
  {
    title: 'Reports',
    category: FaqCategory.Reports,
    icon: 'file-lines',
    iconCLass: 'text-zt_purple',
    file: 'assets/reports.faq.json',
  },
  {
    title: 'Plans',
    category: FaqCategory.Plans,
    icon: 'lightbulb',
    iconCLass: 'text-yellow-500',
    file: 'assets/plans.faq.json',
  },
  {
    title: 'Pricing',
    category: FaqCategory.Pricing,
    icon: 'dollar-sign',
    iconCLass: 'text-green-500',
    file: 'assets/pricing.faq.json',
  },
  {
    title: 'Promos',
    category: FaqCategory.Promos,
    icon: 'tags',
    iconCLass: 'text-zt_purple',
    file: 'assets/promos.faq.json',
  },
  // {
  //   title: 'Integrations',
  //   category: FaqCategory.Integrations,
  //   icon: 'code',
  //   iconCLass: 'text-blue-500',
  //   file: 'assets/integrations.faq.json',
  // },
  {
    title: 'Managing Account',
    category: FaqCategory['Managing Account'],
    icon: 'gear',
    iconCLass: 'text-gray-500',
    file: 'assets/managing-account.faq.json',
  },
  {
    title: 'Trouble Shooting',
    category: FaqCategory['Trouble Shooting'],
    icon: 'screwdriver-wrench',
    iconCLass: 'text-blue-500',
    file: 'assets/troubleshooting.faq.json',
  },
]

export default tabs
