export enum FaqCategory {
  'Getting-Started' = 0,
  'Targets' = 1,
  'Target Verification' = 2,
  'Organizations' = 3,
  'Authenticate' = 4,
  'Unauthenticate' = 5,
  'Product' = 6,
  'Scan' = 7,
  'API Security' = 8,
  'Reports' = 9,
  'Plans' = 10,
  'Pricing' = 11,
  'Promos' = 12,
  'Integrations' = 13,
  'Managing Account' = 14,
  'Trouble Shooting' = 15,
}
